"""DXF emission for the vectorize pipeline.

Unlike ``app/pipeline/export.py`` (which only annotates an existing input DXF
with the alignment transform), this writer creates a clean, layered DXF
*from* the detected geometry.  This is the actual deliverable handed to a CAD
operator at the end of the vectorize pipeline.

Output format
-------------
- DXF R2018 (AC1032) — broadly compatible with BricsCAD, AutoCAD, Vectorworks,
  Revit-import-as-CAD-link, Civil 3D.
- Units: metres (``$INSUNITS = 6``) by default.  Override for projects whose
  CAD standards are imperial.
- Each feature class lands on its own layer with a sensible default colour.
- LWPOLYLINE (closed=False) used for wall segments — single-entity per wall
  is easier to select/edit in CAD than individual LINEs.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import ezdxf
import numpy as np


# ``$INSUNITS`` values per the DXF spec.
INSUNITS_METRES = 6
INSUNITS_FEET = 2
INSUNITS_INCHES = 1
INSUNITS_MILLIMETRES = 4


@dataclass
class LayerSpec:
    name: str
    color_aci: int   # AutoCAD Color Index (1=red, 2=yellow, 3=green, 5=blue, 7=white/black)
    lineweight: int = 25   # in 0.01 mm; 25 = 0.25 mm
    description: str = ""


# Default layer map.  Phase 1 shipped WALLS; Phase 4 added OPENINGS; Phase 6
# adds COLUMNS + WINDOWS.  MEP/TEXT remain reserved for future classes.
DEFAULT_LAYER_MAP: dict[str, LayerSpec] = {
    "walls":           LayerSpec("WALLS",           color_aci=3, lineweight=35,
                                  description="Detected wall centrelines"),
    "walls_exterior":  LayerSpec("WALLS_EXTERIOR",  color_aci=5, lineweight=50,
                                  description="Building shell / exterior envelope (heavier line)"),
    "walls_faces":     LayerSpec("WALLS_FACES",     color_aci=8, lineweight=35,
                                  description="Double-line wall faces (thickness-aware)"),
    "rooms":           LayerSpec("ROOMS",           color_aci=4, lineweight=18,
                                  description="Inferred room polygons (closed cycles in the wall graph)"),
    "openings":        LayerSpec("OPENINGS",        color_aci=2, lineweight=18,
                                  description="Detected door openings"),
    "windows":         LayerSpec("WINDOWS",         color_aci=5, lineweight=18,
                                  description="Operator-marked windows"),
    "columns":         LayerSpec("COLUMNS",         color_aci=1, lineweight=35,
                                  description="Detected structural columns"),
    "mep":             LayerSpec("MEP",             color_aci=6, lineweight=18,
                                  description="Detected mechanical / electrical / plumbing"),
    "text":            LayerSpec("TEXT",            color_aci=7, lineweight=18,
                                  description="Recognised text labels (OCR)"),
    "annotation":      LayerSpec("ANNOTATION",      color_aci=4, lineweight=13,
                                  description="Job metadata / annotations"),
}


def write_dxf(
    segments_by_class: dict[str, np.ndarray],
    output_path: Path,
    layer_map: dict[str, LayerSpec] | None = None,
    insunits: int = INSUNITS_METRES,
    annotation_text: Optional[str] = None,
    circles_by_class: Optional[dict[str, list[tuple[tuple[float, float], float]]]] = None,
) -> Path:
    """Write a DXF containing per-class line geometry.

    Parameters
    ----------
    segments_by_class : dict
        Map of class-key → ``(N, 2, 2)`` array of world-coordinate segments
        ``[[x1, y1], [x2, y2]]``.  Class keys must exist in ``layer_map``
        (or :data:`DEFAULT_LAYER_MAP`) — unknown keys are silently dropped
        with a warning written to the ``ANNOTATION`` layer.
    output_path : Path
        Where to write the DXF.  Parent directory will be created if needed.
    layer_map : dict, optional
        Per-class layer specification.  Defaults to :data:`DEFAULT_LAYER_MAP`.
    insunits : int
        DXF ``$INSUNITS`` header value.  Default = 6 (metres).
    annotation_text : str, optional
        Free-text annotation added to the ``ANNOTATION`` layer at the world
        origin.  Useful for traceability ("generated by vectorize job XYZ at
        elevation Z, detector=fld, ...").

    Returns
    -------
    Path
        The ``output_path`` that was written.
    """
    layer_map = layer_map or DEFAULT_LAYER_MAP
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = ezdxf.new(dxfversion="R2018", setup=True)
    doc.header["$INSUNITS"] = insunits
    msp = doc.modelspace()

    # Create every layer up front so the file has all known layer slots even
    # when a class has zero detections this run.  ezdxf 1.x doesn't expose a
    # ``description`` field on layers — store the description as a DXF
    # comment attached to the layer instead.
    for spec in layer_map.values():
        if spec.name in doc.layers:
            continue
        layer = doc.layers.add(
            name=spec.name,
            color=spec.color_aci,
            lineweight=spec.lineweight,
        )
        if spec.description:
            try:
                layer.description = spec.description  # type: ignore[attr-defined]
            except Exception:
                pass   # silently skip when the ezdxf version doesn't support it

    unknown_classes: list[str] = []
    total_entities = 0

    for class_key, segments in segments_by_class.items():
        if class_key not in layer_map:
            unknown_classes.append(class_key)
            continue
        if segments is None or len(segments) == 0:
            continue

        layer_name = layer_map[class_key].name
        for seg in segments:
            # LWPOLYLINE with two vertices = a line, but selects/edits as a
            # single entity in CAD (better operator UX than individual LINEs).
            msp.add_lwpolyline(
                [(float(seg[0, 0]), float(seg[0, 1])),
                 (float(seg[1, 0]), float(seg[1, 1]))],
                dxfattribs={"layer": layer_name},
            )
            total_entities += 1

    # v4: optional circles_by_class (round columns).  Emitted as native DXF
    # CIRCLE entities instead of polyline rectangles — this is what the
    # commercial CAD drawings in the user's reference image use for round
    # columns.  Drafters can hatch round columns with one click in AutoCAD.
    if circles_by_class:
        for class_key, circles in circles_by_class.items():
            if class_key not in layer_map:
                unknown_classes.append(class_key)
                continue
            if not circles:
                continue
            layer_name = layer_map[class_key].name
            for (cx, cy), radius in circles:
                msp.add_circle(
                    center=(float(cx), float(cy)),
                    radius=float(radius),
                    dxfattribs={"layer": layer_name},
                )
                total_entities += 1

    # Annotation: small text at world origin describing the run.
    if annotation_text or unknown_classes:
        note = annotation_text or ""
        if unknown_classes:
            note = (note + "  " if note else "") + (
                f"(skipped unknown classes: {', '.join(sorted(set(unknown_classes)))})"
            )
        msp.add_text(
            note,
            dxfattribs={
                "layer": layer_map["annotation"].name,
                "height": 0.10,   # 10 cm — readable at typical plan scales
            },
        ).set_placement((0.0, 0.0, 0.0))

    doc.saveas(str(output_path))
    return output_path


def write_walls_dxf(
    wall_segments: np.ndarray,
    output_path: Path,
    annotation_text: Optional[str] = None,
    insunits: int = INSUNITS_METRES,
) -> Path:
    """Convenience wrapper for the walls-only case (Phase 1)."""
    return write_dxf(
        {"walls": wall_segments},
        output_path,
        annotation_text=annotation_text,
        insunits=insunits,
    )
